version: '3.8'

services:
  flask_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    expose:
      - "5000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - flask_app
